#!/usr/bin/env python3
"""Emit a topdown-viewer spatial config (visualization/configs/) per built
households-pipeline household, so every timeline replays in the same
localhost viewer as the older sets (visualization/serve.py).

ADAPTED 2026-08-28 from src/revamp_v2/make_viewer_configs.py (source
commit 0d7c3b5e3723d1bf1f46c99dae40780fbde0951e) for the self-contained
src/households package. Owned copy: edit in place. Changes: reads
profiles/households/generated/<model>/<hh_id>/, config names carry the
households prefix, and it can run the spatializer itself (--spatialize)
so a freshly generated household appears in the viewer without a second
command.

The viewer's dataset list is NOT written here: visualization/serve.py
rebuilds traces.json from what is on disk every time it starts, so there is
one writer of that file and nothing to keep in sync.

Room-level fidelity, same as the hand-made hh_001 config: symbolic rooms
map onto scene 102343992's ground-floor suite; receptacle anchors are
deterministic fractions of the room bbox laid out on a small grid (not
matched to real furniture — the viewer only needs stable, distinct spots).

Usage:
  python -m households.make_viewer_configs [--slug gpt-5.6-terra] \
      [--household hh_001] [--spatialize]
  # then: (cd visualization && python serve.py) -> http://127.0.0.1:8710/
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
GENERATED = REPO / "profiles" / "households" / "generated"
VIZ = REPO / "visualization"
SCENE = "102343992"

# symbolic room -> scene region (the same suite hh_001 uses, plus the
# other bedrooms of the house for multi-bedroom households)
ROOM_MAP = {
    "bedroom": "bedroom.004", "bedroom_1": "bedroom.004",
    "bedroom_2": "bedroom", "bedroom_3": "bedroom.001",
    "bedroom_4": "bedroom.002",
    "living": "tv", "kitchen": "kitchen", "bathroom": "bathroom.001",
    "entry": "hallway.003",
}
GRID = [(0.22, 0.25), (0.5, 0.25), (0.78, 0.25), (0.22, 0.55),
        (0.5, 0.55), (0.78, 0.55), (0.22, 0.82), (0.5, 0.82), (0.78, 0.82)]


def _spec_path(hh_dir: pathlib.Path) -> str:
    spec = (hh_dir / "expanded_motions.yaml").resolve()
    try:
        return str(pathlib.Path("..") / ".." / spec.relative_to(REPO))
    except ValueError:
        return str(spec)


def relation_for(rid: str) -> str:
    if "floor" in rid:
        return "floor"
    if "hook" in rid:
        return "hook"
    return "on_surface"


def make_config(hh_dir: pathlib.Path) -> pathlib.Path:
    # rule_based/story_calendar write routine_program.yaml; storyfirst
    # writes program.yaml (its story days ARE the schedule). Either is
    # the same shape from `receptacles` down, which is all this needs.
    spec = next((hh_dir / n for n in ("routine_program.yaml",
                                      "program.yaml")
                 if (hh_dir / n).exists()), None)
    assert spec is not None, f"{hh_dir}: no program file"
    program = yaml.safe_load(spec.read_text())
    rooms_used = {r["room"] for r in program["receptacles"]}
    unknown = rooms_used - set(ROOM_MAP)
    assert not unknown, f"{hh_dir.name}: no scene mapping for rooms {unknown}"
    per_room: dict[str, int] = {}
    receptacles = {}
    for r in program["receptacles"]:
        i = per_room.get(r["room"], 0)
        per_room[r["room"]] = i + 1
        fx, fz = GRID[i % len(GRID)]
        receptacles[r["id"]] = {"anchor": [fx, fz],
                                "relation": relation_for(r["id"])}
    cfg = {
        "household": program["household"],
        # spatialize.py reads receptacles + placements in the revamp_v1
        # object_motions shape; simulate.py emits exactly that alongside
        # the program. The path is relative to the config's own directory
        # (spatialize.py's convention) for households inside the repo, and
        # absolute for an --out-root anywhere else — both resolve there.
        "schedule_spec": _spec_path(hh_dir),
        "scene_assets": f"../assets/{SCENE}",
        "room_map": {room: ROOM_MAP[room] for room in sorted(rooms_used)},
        "receptacles": receptacles,
        "elsewhere": {"pos": [6.5, -12.5], "label": "AWAY (outside)"},
        "view_margin_m": 2.0,
    }
    slug = hh_dir.parent.name           # model slug
    out = (VIZ / "configs" /
           f"households_{slug}_{hh_dir.name}_{SCENE}.yaml")
    out.write_text(
        "# AUTO-GENERATED by python -m households.make_viewer_configs —\n"
        "# room-level grounding of a households-pipeline household into\n"
        f"# scene {SCENE}.\n"
        + yaml.safe_dump(cfg, sort_keys=False, width=100))
    return out


def spatialize(config: pathlib.Path, timeline: pathlib.Path) -> None:
    """Run visualization/spatialize.py, which writes the trace.json the
    viewer lists a household by. Without it a generated timeline is on
    disk but invisible in the viewer."""
    import subprocess
    import sys as _sys
    subprocess.run(
        [_sys.executable, str(VIZ / "spatialize.py"), str(config),
         "--timeline", str(timeline)],
        cwd=VIZ, check=True)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--slug", default=None,
                    help="model slug under profiles/households/generated "
                         "(default: all found)")
    ap.add_argument("--household", default=None,
                    help="one household id, e.g. hh_001 (default: all)")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--spatialize", action="store_true",
                    help="also write trace.json for each timeline, which "
                         "is what publishes it to the viewer")
    args = ap.parse_args()
    if not GENERATED.is_dir():
        sys.exit(f"nothing generated yet under {GENERATED}")
    slugs = ([args.slug] if args.slug else
             sorted(d.name for d in GENERATED.iterdir() if d.is_dir()))
    if not slugs:
        sys.exit(f"no model directories under {GENERATED}")
    for slug in slugs:
        hh_dirs = sorted((GENERATED / slug).glob("hh_*"))
        if args.household:
            hh_dirs = [d for d in hh_dirs if d.name == args.household]
        for hh_dir in hh_dirs:
            if not (hh_dir / "program.yaml").exists():
                continue
            cfg = make_config(hh_dir)
            timeline = hh_dir / f"timeline_seed{args.seed}"
            note = ""
            if not timeline.exists():
                note = " (no timeline yet)"
            elif args.spatialize:
                spatialize(cfg, timeline)
                note = " -> trace.json"
            print(f"{hh_dir.name}: {cfg.name}{note}")


if __name__ == "__main__":
    main()
