#!/usr/bin/env python3
"""Emit a topdown-viewer spatial config (visualization/configs/) per built
revamp_v2 household, so every timeline replays in the SAME localhost viewer
as revamp_v1 (visualization/serve.py).

The viewer's dataset list is NOT written here: visualization/serve.py
rebuilds traces.json from what is on disk every time it starts, so there is
one writer of that file and nothing to keep in sync.

Room-level fidelity, same as the hand-made hh_001 config: symbolic rooms
map onto scene 102343992's ground-floor suite; receptacle anchors are
deterministic fractions of the room bbox laid out on a small grid (not
matched to real furniture — the viewer only needs stable, distinct spots).

Usage:
  python src/revamp_v2/make_viewer_configs.py [--slug qwen3-32b]
  # then: (cd visualization && python serve.py)  ->  http://127.0.0.1:8710/
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent
VIZ = REPO / "visualization"
SCENE = "102343992"

# symbolic room -> scene region (the same suite hh_001 uses, plus the
# other bedrooms of the house for multi-bedroom households)
ROOM_MAP = {
    "bedroom": "bedroom.004", "bedroom_1": "bedroom.004",
    "bedroom_2": "bedroom", "bedroom_3": "bedroom.001",
    "bedroom_4": "bedroom.002",
    "living": "tv", "kitchen": "kitchen", "bathroom": "bathroom.001",
    "entry": "hallway.003",
}
GRID = [(0.22, 0.25), (0.5, 0.25), (0.78, 0.25), (0.22, 0.55),
        (0.5, 0.55), (0.78, 0.55), (0.22, 0.82), (0.5, 0.82), (0.78, 0.82)]


def _spec_path(hh_dir: pathlib.Path) -> str:
    spec = (hh_dir / "expanded_motions.yaml").resolve()
    try:
        return str(pathlib.Path("..") / ".." / spec.relative_to(REPO))
    except ValueError:
        return str(spec)


def relation_for(rid: str) -> str:
    if "floor" in rid:
        return "floor"
    if "hook" in rid:
        return "hook"
    return "on_surface"


def make_config(hh_dir: pathlib.Path) -> pathlib.Path:
    program = yaml.safe_load((hh_dir / "routine_program.yaml").read_text())
    rooms_used = {r["room"] for r in program["receptacles"]}
    unknown = rooms_used - set(ROOM_MAP)
    assert not unknown, f"{hh_dir.name}: no scene mapping for rooms {unknown}"
    per_room: dict[str, int] = {}
    receptacles = {}
    for r in program["receptacles"]:
        i = per_room.get(r["room"], 0)
        per_room[r["room"]] = i + 1
        fx, fz = GRID[i % len(GRID)]
        receptacles[r["id"]] = {"anchor": [fx, fz],
                                "relation": relation_for(r["id"])}
    cfg = {
        "household": program["household"],
        # spatialize.py reads receptacles + placements in the revamp_v1
        # object_motions shape; simulate.py emits exactly that alongside
        # the program. The path is relative to the config's own directory
        # (spatialize.py's convention) for households inside the repo, and
        # absolute for an --out-root anywhere else — both resolve there.
        "schedule_spec": _spec_path(hh_dir),
        "scene_assets": f"../assets/{SCENE}",
        "room_map": {room: ROOM_MAP[room] for room in sorted(rooms_used)},
        "receptacles": receptacles,
        "elsewhere": {"pos": [6.5, -12.5], "label": "AWAY (outside)"},
        "view_margin_m": 2.0,
    }
    slug = hh_dir.parent.name           # model slug
    method = hh_dir.parent.parent.name  # rule_based / freeform / ...
    out = (VIZ / "configs" /
           f"revamp_v2_{method}_{slug}_{hh_dir.name}_{SCENE}.yaml")
    out.write_text(
        "# AUTO-GENERATED by src/revamp_v2/make_viewer_configs.py — room-\n"
        "# level grounding of a revamp_v2 household into scene "
        f"{SCENE}.\n" + yaml.safe_dump(cfg, sort_keys=False, width=100))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--slug", default=None,
                    help="'<method>/<model-slug>' under profiles/revamp_v2, "
                         "e.g. rule_based/qwen3.8-27b (default: all found)")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    root = REPO / "profiles" / "revamp_v2"
    # profiles/revamp_v2/<method>/<model-slug>/hhN
    slugs = ([args.slug] if args.slug else
             sorted(f"{m.name}/{d.name}"
                    for m in root.iterdir() if m.is_dir()
                    for d in m.iterdir()
                    if d.is_dir() and (d / "hh1").exists()))
    if not slugs:
        sys.exit("no built households found under profiles/revamp_v2/")
    for slug in slugs:
        for hh_dir in sorted((root / slug).glob("hh*"),
                             key=lambda p: int(p.name[2:])):
            if not (hh_dir / "routine_program.yaml").exists():
                continue
            cfg = make_config(hh_dir)
            timeline = hh_dir / f"timeline_seed{args.seed}"
            print(f"{hh_dir.name}: {cfg.name}"
                  + ("" if timeline.exists() else " (no timeline yet)"))


if __name__ == "__main__":
    main()
