name: act_p2_sick15
sim_dir: ../data/situation_sim/confshift/sick15
events: {sick_day: {weekday: 0.15, weekend: 0.02}}
patrol_hours: 2
patrol_times: null
classes: null
per_day: 32
oversample: 96
questions: activity
timetable_bin_hours: 2
