name: act_p2_ev10
sim_dir: ../data/situation_sim/confshift/ev10
events: {sick_day: {weekday: 0.10, weekend: 0.02}, guest_visit: {weekday: 0.10, weekend: 0.14}}
patrol_hours: 2
patrol_times: null
classes: null
per_day: 32
oversample: 128
questions: activity
timetable_bin_hours: 2
