name: B_t03-15
sim_dir: ../data/situation_sim/confshift/base
events: {}
patrol_hours: 4
patrol_times: 03:00,15:00
classes: [mug, glass, bowl, plate, water_bottle, pan, pot, spatula, cutting_board, snack_bowl, shoes, jacket, scarf, keys, wallet, backpack, laptop, charger, headphones, tablet, glasses, book, blanket, razor, skincare, dog_leash, dog_food_bag, notebook, pen, remote]
per_day: 32
oversample: 80
