name: C_t03
sim_dir: ../data/situation_sim/confshift/base
events: {}
patrol_hours: 4
patrol_times: 03:00
classes: [mug, glass, bowl, plate, water_bottle, pan, pot, spatula, cutting_board, snack_bowl, mixing_bowl, baking_tray, serving_dish, shoes, jacket, scarf, dog_food_bag, dog_bowl, dog_toy, gym_bag, keys, wallet]
per_day: 32
oversample: 80
