name: A_t03-15
sim_dir: ../data/situation_sim/confshift/base
events: {}
patrol_hours: 4
patrol_times: 03:00,15:00
classes: [mug, glasses, bowl, glass, tablet, razor, water_bottle, plate, snack_bowl, recipe_book, backpack, skincare, laptop, shoes, pot, vitamins, serving_dish, headphones, charger, dog_food_bag, jacket, dog_leash]
per_day: 32
oversample: 80
